### ISSUE TITLE
can not find sourceanalyzer from FORTIFY_HOME & PATH

### ISSUE THREAD

**Issue by anoyo-lin** [jenkinsci/fortify-plugin#21] opened 2020-08-07 08:35 UTC
"FORTIFY_HOME=/tech/Fortify"
"PATH=/tech/nvm/versions/node/v11.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tech/Fortify/bin:/tech/apache-ant-1.9.14/bin"

i reviewed the src code of SCAStep & Step, and put fortifySCA at /tech/Fortify/ 
and sourceanalyzer in /tech/Fortify/sourceanalyzer

but the plugin can not found executable in my docker container.
it will show error msg in v19 and use the sourceanalyzer in PATH, but for 20.0.1.33, it will throw new FILENOTFOUNDEXCEPTION.

[devops@73a08d678758 ene_feature_provisioning-service]$ stat /tech/Fortify/bin/sourceanalyzer
  File: '/tech/Fortify/bin/sourceanalyzer'
  Size: 236528          Blocks: 464        IO Block: 4096   regular file
Device: 31h/49d Inode: 321         Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 9001/  devops)   Gid: ( 9001/  devops)
Access: 2020-07-22 14:26:14.000000000 +0800
Modify: 2020-07-22 14:26:14.000000000 +0800
Change: 2020-07-23 16:59:09.257453731 +0800
 Birth: -

how to mitigate this one?

**Comment by anoyo-lin** [comment] 2020-08-07 08:50
i downgraded to 19.2.30
and 
10:44:24  Running FortifyTranslate step
10:44:24  Fortify Jenkins plugin v 19.1.29
10:44:24  Launching Fortify SCA translate command
10:44:24  executable not found: sourceanalyzer
**10:44:24  	home: null
10:44:24  	path: null**
10:44:24  	workspace: /app/jenkins/workspace/est_feature_provisioning-service
10:44:24  Running Maven 3 translation
10:44:24  executable not found: mvn
**10:44:24  	home: null
10:44:24  	path: null**

**Comment by ashnazg** [comment] 2020-09-02 18:55
I'm inclined to concur on your observation that "it will show error msg in v19 and use the sourceanalyzer in PATH, but for 20.0.1.33, it will throw new FILENOTFOUNDEXCEPTION".  The build pipelines I've been using for almost a year with the 19.x client did work using the plugin, but the output always looked to me like it was saying "can't find the executable"... and then it would run the executable anyway and succeed.  And now I can't get the 20.x client to work with the plugin at all from inside a container.  I can run the commands just fine via "sh" kickoffs in the pipeline step, but the plugin can't even manage the fortifyUpdate step for me.

**Comment by ashnazg** [comment] 2020-09-02 19:45
Our suspicion is that this working from a docker container might have not actually worked by design back in 19.x, and only did succeed in working because `FortifyStep::getExecutable() did NOT throw an exception on line [88](https://github.com/jenkinsci/fortify-plugin/blob/master/src/main/java/com/fortify/plugin/jenkins/steps/FortifyStep.java#L88).  We're thinking the 19.x code here didn't find the executable, but because it continued rather than erroring out, the container was given the _chance_ to run, and it succeeded.

I'll issue a PR to revert just that exception throw, on the premise that we should let the container still attempt to run the requested executable even if the plugin's runtime checker is not itself able to find it.

**Comment by vrulevskyi** [comment] 2020-10-21 15:33
Hi @anoyo-lin, please see the suggestion for accessing SCA_and_Apps executables with Fortify Jenkins plugin when Jenkins is being run in the Docker in https://github.com/jenkinsci/fortify-plugin/pull/29 and if it solves your problem. Thanks.

**Comment by vrulevskyi** [comment] 2020-11-19 21:08
Closing the issue for now. If you still need further help, please, reopen this issue or create another one. Regards

**Closed by vrulevskyi** 2020-11-19 21:08 UTC

**Comment by ksg97031** [comment] 2020-12-08 10:57
@vrulevskyi Could you please verify https://github.com/jenkinsci/fortify-plugin/issues/42 is the same issue?
